apiVersion: v1
kind: Service
metadata:
  name: demo-test
  namespace: namespace-workflow-1713753850676
spec:
  type: LoadBalancer
  selector:
    app: demo-test
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080